call npx vercel env add DATABASE_URL production --value "postgresql://postgres.pxzpakpzdblcaifhglql:Erioluwa204@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true" --yes
call npx vercel env add DIRECT_URL production --value "postgresql://postgres.pxzpakpzdblcaifhglql:Erioluwa204@aws-0-eu-west-1.pooler.supabase.com:5432/postgres" --yes
call npx vercel env add JWT_SECRET production --value "9d47ef94c8740658cb50836eae0c43ac04ddaf944cb8b7693276d3ef7dab7eb6" --yes
call npx vercel env add EMAIL_API_SECRET production --value "PROLINK_INTERNAL_SECRET_888" --yes
call npx vercel env add SMTP_USER production --value "prolink.verify@gmail.com" --yes
call npx vercel env add SMTP_PASS production --value "aacjcuqkwdtnyccg" --yes
call npx vercel env add SMTP_NOTIFICATIONS_USER production --value "prolink.notifications@gmail.com" --yes
call npx vercel env add SMTP_NOTIFICATIONS_PASS production --value "tmibuibxgiekzael" --yes
call npx vercel env add FRONTEND_ORIGIN production --value "https://prolink-eight.vercel.app" --yes
call npx vercel env add NODE_ENV production --value "production" --yes
call npx vercel env add LOG_LEVEL production --value "info" --yes
call npx vercel env add PLATFORM_FEE_PERCENT production --value "10" --yes
call npx vercel env add MIN_BID_AMOUNT production --value "500" --yes
call npx vercel env add AUTO_RELEASE_DAYS production --value "7" --yes
